"""update image table

Revision ID: 400ae6f28ca4
Revises: fa412bf2107c
Create Date: 2025-04-28 17:49:57.467414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '400ae6f28ca4'
down_revision: Union[str, None] = 'fa412bf2107c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('normal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('image', sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('image', 'normal')
    op.drop_column('image', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('image', sa.Column('normal', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('image', 'thumbnail_url')
    op.drop_column('image', 'normal_url')
    # ### end Alembic commands ###
