"""update image nullable for album table

Revision ID: ad0a6261a40e
Revises: 400ae6f28ca4
Create Date: 2025-04-28 18:06:23.568063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ad0a6261a40e'
down_revision: Union[str, None] = '400ae6f28ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('album_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'image', 'album', ['album_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'album_id')
    # ### end Alembic commands ###
